language: ruby
cache: bundler
dist: trusty
sudo: required

rvm:
- 2.3.7
- 2.4.4
- 2.5.1

before_install:
  - sudo apt-get update
  - sudo apt-get install python
  - nvm install node
  - nvm use node

install:
  - pip install --user bumpversion
  - npm install -g semantic-release
  - npm install -g @semantic-release/exec
  - bundle install
  # - 'if [ "${TRAVIS_TAG}" = "${TRAVIS_BRANCH}" ]; then cd appscan; make asoc-tool; cd ../; fi'
  - cd appscan; make asoc-tool; cd ../;
before_script:
# - 'if [ "${TRAVIS_TAG}" = "${TRAVIS_BRANCH}" ]; then chmod a+x ./appscan/ASOC.sh; fi'
- chmod a+x ./appscan/ASOC.sh;
script:
- bundle exec rake
# - 'if [ "${TRAVIS_TAG}" = "${TRAVIS_BRANCH}" ]; then ./appscan/ASOC.sh; fi'
- ./appscan/ASOC.sh;

before_deploy:
  - bundle exec rake test:appveyor_status

deploy:
  - provider: script
    script: npx travis-deploy-once "npx semantic-release"
    on:
      branch: master
      rvm: 2.5.1

  - provider: rubygems
    api_key: $RUBYGEMS_API_KEY
    gem: ibm_watson
    on:
      branch: master
      rvm: 2.5.1

matrix:
  fast_finish: true

notifications:
  email: false