language: ruby
cache: bundler
sudo: required

rvm:
- 2.3.7
- 2.4.4
- 2.5.1

before_install:
  - sudo apt-get update
  - sudo apt-get install python
  - nvm install node
  - nvm use node

install:
  - pip install --user bumpversion
  - npm install @semantic-release/exec
  - bundle install

script:
- bundle exec rake

deploy:
  - provider: script
    script: npx travis-deploy-once "npx semantic-release"

  - provider: rubygems
    api_key: $RUBYGEMS_API_KEY
    gem: watson_apis
    on:
      branch: master
      rvm: 2.5.1

matrix:
  fast_finish: true