version: 1.0.{build}-{branch}
skip_tags: true

cache:
  - vendor/bundle

environment:
  matrix:
    - RUBY_VERSION: 23
    - RUBY_VERSION: 24
    - RUBY_VERSION: 25

init:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%

install:
  - bundle config build.eventmachine --platform ruby
  - bundle install

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake

deploy: off
matrix:
  fast_finish: true