version: 1.0.{build}-{branch}
skip_tags: true

cache:
  - vendor/bundle

environment:
  matrix:
    - RUBY_VERSION: 23-x64
    - RUBY_VERSION: 24-x64
    - RUBY_VERSION: 25-x64

init:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%

install:
  - ps: |
      if ($Env:RUBY_VERSION -match "^23" ) {
        ((New-Object Net.WebClient).DownloadFile('https://curl.haxx.se/ca/cacert.pem', "$env:TMP\ca-cert.pem"))
        set SSL_CERT_FILE=%TMP%\ca-cert.pem
      }
  - bundle install
  - gem uninstall -a -x --force eventmachine
  - gem install eventmachine --platform ruby --no-rdoc --no-ri

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake

deploy: off
matrix:
  fast_finish: true